server:
  port: 8080
spring:
  application:
    name: Project HSH

  #  # MAIL
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: theanh08042004@gmail.com
  #    password: lywt qpvr vklq fiuc
  #    protocol: smtp
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls.enable: true

  # DATABASE
  datasource:
    url: jdbc:mysql://employee_db:3306/sgiant_project
    # url: jdbc:mysql://localhost:3306/sgiant_project
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

# JWT
jwt:
  secret: 753474857438754387594385743975348574893759843753498776576576575765634545435365346534645645364565465347657547465
  expiration: 863999999
  refresh:
    secret: 123454857438754387594385743975348574893759843753498776576576575765634545435365346534645645364565465347657554321
    expiration: 864000000
  algorithms: HmacSHA256
application:
  default-current-page: 1
  default-page-size: 30

# SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
