name: 🚀 Auto Deploy to VPS

on:
  push:
    branches:
      - main # hoặc branch bạn dùng

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📡 SSH & Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/nguyen_khanh_trinh
            git pull origin main
            docker compose down
            docker compose up -d --build
